package com.pepperkim.baseframework.api.model.common

enum class ApiErrorCode(val data: Int) {
	SUCCESS(200),
//	INTERNAL_ERROR(1000),
//	RUNTIME_ERROR(1001),
//	DATABASE_ERROR(1002),
//	PARAMETER_ERROR(1003),
//	NOT_FOUND_ERROR(1004),
//	UNAUTHORIZED_ERROR(1005),
//	INVALID_APP_AGENT_ERROR(1006),
//	DATABASE_EXECUTE(1007),
//	NOT_SUPPORTED(1008),
//	DUPLICATE_USER(1009),
//	ONSET_PARAMETER_ERROR(1010),
//	FILE_UPLOAD_FAILED(1061),
//	FILE_UPLOAD_FILE_NOT_FOUND(1062),
//	FILE_UPLOAD_SIZE_EXCEEDED(1063),
//	FILE_UPLOAD_UNSUPPORTED_FILE_TYPE(1064),
//	FILE_UPLOAD_IMAGE_SIZE_EXCEEDED(1071),
//	FILE_UPLOAD_VIDEO_SIZE_EXCEEDED(1072),
//	FILE_UPLOAD_MUSIC_SIZE_EXCEEDED(1073),
//	FILE_UPLOAD_DATA_SIZE_EXCEEDED(1074),
	UNKNOWN_ERROR(9001);

	companion object {
		fun dataOf(data: Int, defaultValue: ApiErrorCode = UNKNOWN_ERROR) = values().firstOrNull { it.data == data } ?: defaultValue
	}
}